"""
Django settings for whatreach project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=ny=#@*df2v=17a-4jwnsv#i26-fsy&-64zz0s$5arl2-h#d+1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'ghl_integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # GoHighLevel token management middleware
    'ghl_integration.middleware.GoHighLevelTokenMiddleware',
    'ghl_integration.middleware.GoHighLevelTokenHealthMiddleware',
]

ROOT_URLCONF = 'whatreach.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whatreach.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GoHighLevel OAuth Configuration
GHL_CLIENT_ID = '68a6c0fcfe0b684454802406-mel721b5'  # Replace with your actual client ID
GHL_CLIENT_SECRET = '2262c009-6eda-4953-8005-7dfd1791db16'  # Replace with your actual client secret
GHL_REDIRECT_URI = 'https://814e0c0adec4.ngrok-free.app/app/callback/'  # Update for production

# Django Crontab Configuration
CRONJOBS = [
    # Refresh GoHighLevel tokens every hour
    ('0 * * * *', 'ghl_integration.cron.refresh_expired_tokens'),
    
    # Daily token health check at 2 AM
    ('0 2 * * *', 'ghl_integration.cron.daily_token_health_check'),
    
    # Weekly bulk refresh on Sundays at 3 AM
    ('0 3 * * 0', 'ghl_integration.cron.weekly_bulk_refresh'),
]

# Crontab settings
CRONTAB_LOCK_JOBS = True  # Prevent multiple instances of the same job
CRONTAB_COMMAND_PREFIX = 'DJANGO_SETTINGS_MODULE=whatreach.settings'
CRONTAB_PYTHON_EXECUTABLE = 'python'


