# Generated by Django 5.2.4 on 2025-08-21 09:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoHighLevelIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_id', models.CharField(help_text='GoHighLevel location ID', max_length=255, unique=True)),
                ('location_name', models.CharField(blank=True, help_text='GoHighLevel location name', max_length=255)),
                ('user_id', models.CharField(blank=True, help_text='GoHighLevel user ID', max_length=255)),
                ('user_email', models.EmailField(blank=True, help_text='GoHighLevel user email', max_length=254)),
                ('access_token', models.TextField(help_text='GoHighLevel access token')),
                ('refresh_token', models.TextField(blank=True, help_text='GoHighLevel refresh token')),
                ('token_type', models.CharField(default='Bearer', help_text='Token type', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the app was installed')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time the integration was used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the integration is active')),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Company phone', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Company website')),
            ],
            options={
                'verbose_name': 'GoHighLevel Integration',
                'verbose_name_plural': 'GoHighLevel Integrations',
                'db_table': 'ghl_integration',
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='GoHighLevelWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100)),
                ('event_data', models.JSONField(help_text='Webhook event data')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When webhook was received')),
                ('processed', models.BooleanField(default=False, help_text='Whether webhook was processed')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='ghl_integration.gohighlevelintegration')),
            ],
            options={
                'verbose_name': 'GoHighLevel Webhook',
                'verbose_name_plural': 'GoHighLevel Webhooks',
                'db_table': 'ghl_webhook',
                'ordering': ['-received_at'],
            },
        ),
    ]
