# Generated by Django 5.2.4 on 2025-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gohighlevelintegration',
            name='company_id',
            field=models.CharField(blank=True, help_text='GoHighLevel company ID', max_length=255),
        ),
    ]
