# Generated by Django 5.2.4 on 2025-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0002_gohighlevelintegration_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gohighlevelintegration',
            name='is_bulk_installation',
            field=models.BooleanField(default=False, help_text='Whether this is a bulk installation'),
        ),
        migrations.AddField(
            model_name='gohighlevelintegration',
            name='refresh_token_id',
            field=models.CharField(blank=True, help_text='GoHighLevel refresh token ID', max_length=255),
        ),
        migrations.AddField(
            model_name='gohighlevelintegration',
            name='scope',
            field=models.TextField(blank=True, help_text='OAuth scopes granted'),
        ),
        migrations.AddField(
            model_name='gohighlevelintegration',
            name='user_type',
            field=models.CharField(blank=True, help_text='Token user type (Company/Location)', max_length=50),
        ),
    ]
