# Generated by Django 5.2.4 on 2025-08-22 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0003_gohighlevelintegration_is_bulk_installation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(help_text="Name of the WhatsApp API provider (e.g., 'Twilio', 'MessageBird', 'Custom Provider')", max_length=100)),
                ('provider_url', models.URLField(blank=True, help_text='Base URL of the WhatsApp API provider')),
                ('access_token', models.TextField(help_text='WhatsApp API provider access token')),
                ('token_type', models.CharField(default='Bearer', help_text='Token type (Bearer, API Key, etc.)', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration time (if applicable)', null=True)),
                ('scopes', models.TextField(blank=True, help_text='API scopes/permissions granted to this token')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp phone number associated with this token', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Name of the WhatsApp account', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active and can be used')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this token was used for API calls')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this token has been used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this token was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this token was last updated')),
                ('integration', models.OneToOneField(help_text='Associated GoHighLevel integration', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_token', to='ghl_integration.gohighlevelintegration')),
            ],
            options={
                'verbose_name': 'WhatsApp Access Token',
                'verbose_name_plural': 'WhatsApp Access Tokens',
                'db_table': 'whatsapp_access_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'is_active'], name='whatsapp_ac_integra_4a6dc1_idx'), models.Index(fields=['provider_name', 'is_active'], name='whatsapp_ac_provide_942c8e_idx'), models.Index(fields=['expires_at'], name='whatsapp_ac_expires_bda586_idx')],
            },
        ),
    ]
