# Generated by Django 5.2.4 on 2025-08-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0004_whatsappaccesstoken'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappaccesstoken',
            name='whatsapp_ac_provide_942c8e_idx',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='provider_url',
        ),
    ]
