# Generated by Django 5.2.4 on 2025-08-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_integration', '0005_remove_provider_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whatsappaccesstoken',
            name='whatsapp_ac_integra_4a6dc1_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappaccesstoken',
            name='whatsapp_ac_expires_bda586_idx',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='token_type',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='whatsappaccesstoken',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='whatsappaccesstoken',
            name='access_token',
            field=models.TextField(help_text='WhatsApp access token'),
        ),
        migrations.AddIndex(
            model_name='whatsappaccesstoken',
            index=models.Index(fields=['integration'], name='whatsapp_ac_integra_17405b_idx'),
        ),
    ]
